baseURL: https://pixelcat31415.github.io/blog/
title: Nyanyannya

permalinks:
  posts: "/:year/:month/:filename/"

theme: eureka

paginate: 10
copyright: 
enableEmoji: true
enableGitInfo: false
summaryLength: 75

defaultContentLanguage: zh
hasCJKLanguage: true
defaultContentLanguageInSubdir: false

# Uncomment for google analytics
# googleAnalytics: UA-123-45

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: always
  # useResourceCacheWhen: never