mainSections:
  - posts
description: Eureka is a elegant and powerful theme for Hugo.

repoEditURL:

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme: dark

# Colors and fonts. Default style is data/styles/default.yaml/
style: custom

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: PixelCat
publisherLogo:

# highlight:
#   handler: highlightjs

#   highlightjs:
#     # highlight.js doesn't bundle every language. So please specify additional languages you want here.
#     # See https://github.com/highlightjs/cdn-release/tree/main/build/languages for available languages.
#     languages:
#       - dart
#     # See https://github.com/highlightjs/cdn-release/tree/main/build/styles for available styles.
#     style: base16/monokai

math:
  handler: katex
  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
